// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication.Context;

namespace WebApplication.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20200911070037_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication.Models.Mahasiswa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Jenis_Kelamin")
                        .IsRequired()
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Jurusan")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Kampus")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("NPM")
                        .IsRequired()
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NPM")
                        .IsUnique();

                    b.ToTable("TB_M_Mahasiswa");
                });
#pragma warning restore 612, 618
        }
    }
}
